### PR TITLE
用箭头函数来解决this指向的问题

### PR DESCRIPTION
**Pull request by Jiyr0119**
大佬  我想问一下  您用that保存this指向，是为了代码可阅读性更高吗。如果是我多此一举了哈哈，亲测改完之后是没问题的

### CODE REVIEW

**Comment by fthux** [comment]
@Jiyr0119 因为代码比较乱，有的回调里使用的箭头函数，有的使用的是 es5 的 function callback，顺手就把 that = this 写上去了 。。。

**Review by fthux — COMMENTED** [review]
push 错了吧，你应该自己创建一个库去 push 吧

**Comment by Jiyr0119** [comment]
是的 我点错了。不好意思




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            高俊杰
                            
                            
                                
                                    邮箱：jiyr0119@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制


在2019年04月22日 11:21，myvin 写道： @myvin commented on this pull request.

push 错了吧，你应该自己创建一个库去 push 吧

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/myvin/quietweather","title":"myvin/quietweather","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/myvin/quietweather"}},"updates":{"snippets":[{"icon":"PERSON","message":"@myvin commented on #1"}],"action":{"name":"View Pull Request","url":"https://github.com/myvin/quietweather/pull/1#pullrequestreview-228946905"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/myvin/quietweather/pull/1#pullrequestreview-228946905",
"url": "https://github.com/myvin/quietweather/pull/1#pullrequestreview-228946905",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by fthux** [comment]
@Jiyr0119 👌

**Pull request closed without merging**
